=== comolago/accdf/install/etc/xml/dtd/testsuiteslibrary.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT TestSuitesLibrary ( TestSuites) >
<!ATTLIST TestSuitesLibrary name CDATA #REQUIRED>
<!ATTLIST TestSuitesLibrary title CDATA #REQUIRED>
<!ELEMENT TestSuites ( TestSuite+ ) >
<!ELEMENT TestSuite ( Description, TestCases+ ) >
<!ATTLIST TestSuite name CDATA #REQUIRED>
<!ATTLIST TestSuite title CDATA #REQUIRED>
<!ATTLIST TestSuite group CDATA #IMPLIED>
<!ELEMENT Description (#PCDATA) >
<!ELEMENT TestCases ( TestCase+ ) >
<!ELEMENT TestCase ( Description, Rationale, Inject?, Dependencies?, Tests ) >
<!ATTLIST TestCase name CDATA #REQUIRED>
<!ATTLIST TestCase title CDATA #REQUIRED>
<!ATTLIST TestCase benchmark CDATA #REQUIRED>
<!ATTLIST TestCase id CDATA #REQUIRED>
<!ELEMENT Rationale ( Description ) >
<!ATTLIST Rationale severity CDATA #REQUIRED>
<!ATTLIST Rationale minimum_health CDATA #REQUIRED>
<!ATTLIST Rationale responsible CDATA #REQUIRED>
<!ELEMENT Dependencies ( Dependency+ ) >
<!ELEMENT Dependency EMPTY >
<!ATTLIST Dependency name CDATA #REQUIRED>
<!ATTLIST Dependency title CDATA #REQUIRED>
<!ATTLIST Dependency testsuite CDATA #REQUIRED>
<!ATTLIST Dependency type CDATA #REQUIRED>
<!ELEMENT Tests ( Test+ ) >
<!ELEMENT Test ( TestSteps, Parameters ) >
<!ATTLIST Test name CDATA #REQUIRED>
<!ATTLIST Test title CDATA #REQUIRED>
<!ELEMENT TestSteps ( TestStep+ ) >
<!ELEMENT TestStep EMPTY >
<!ATTLIST TestStep id CDATA #REQUIRED>
<!ATTLIST TestStep src_ip CDATA #IMPLIED>
<!ATTLIST TestStep dst_ip CDATA #IMPLIED>
<!ATTLIST TestStep protocol CDATA #IMPLIED>
<!ATTLIST TestStep port CDATA #IMPLIED>
<!ATTLIST TestStep description CDATA #IMPLIED>
<!ELEMENT Inject ( Classes ) >
<!ELEMENT Classes ( Class+) >
<!ELEMENT Class ( #PCDATA) >
<!ELEMENT Parameters ( Parameter+ ) >
<!ELEMENT Parameter EMPTY >
<!ATTLIST Parameter name CDATA #REQUIRED>
<!ATTLIST Parameter engine CDATA #REQUIRED>
<!ATTLIST Parameter source CDATA #REQUIRED>
<!ATTLIST Parameter query CDATA #REQUIRED>

=== comolago/accdf/install/etc/xml/testsuiteslibrary.xml
<?xml version="1.0"?>
<!DOCTYPE TestSuitesLibrary SYSTEM "dtd/testsuiteslibrary.dtd">
<?xml-stylesheet type="text/xsl" href="xsl/testsuiteslibrary.xsl"?>
<TestSuitesLibrary name="unix" title="UNIX test library">
  <TestSuites>
    <TestSuite name="connectivity" title="Connectivity">
      <Description> bla bla bla</Description>
        <TestCases> 
          <TestCase id="000000" title="LDAP Servers Reachability" name="reachability-ldap" benchmark="checkconn">
          <Description>Perform basic connectivity test of LDAP servers</Description>
          <Rationale severity="Critical" minimum_health="66%" responsible="Telecom Group">
            <Description>LDAP servers should be reachable to allow users authentication and authorization</Description>
          </Rationale>
          <Inject>
            <Classes>
              <Class>LDAP Client</Class>
            </Classes>
          </Inject>
          <Dependencies>
            <Dependency type="testcase" name="testcasename" testsuite="testsuitename" title="Testcase" />  
          </Dependencies>
          <Tests>
            <Test title="Reachability" name="reachability">
              <TestSteps> 
                <TestStep id="${OITA}" src_ip="${SRC_IP}" dst_ip="${DST_IP}" protocol="${PROTOCOL}" port="${PORT}" /> 
              </TestSteps>
              <Parameters>
                 <Parameter name="SRC_IP" engine="SELF" source="variables" query="${TARGET_HOST}" />
                 <Parameter name="DST_IP" engine="XPATH" source="topology.xml" query="/Topology/Server[${TARGET_HOST}]/Peers[@port=389,@port=636]/@ip" />
                 <Parameter name="PORT" engine="XPATH" source="topology.xml" query="/Topology/Server[${TARGET_HOST}]/Peers[@port=389,@port=636]/@port" />
                 <Parameter name="PROTOCOL" engine="XPATH" source="topology.xml" query="/Topology/Server[${TARGET_HOST}]/Peers[@port=389,@port=636]/@protocol" />
              </Parameters> 
            </Test>         
          </Tests>      
        </TestCase> 
      </TestCases>
    </TestSuite>
  </TestSuites>
</TestSuitesLibrary>
